AWSTemplateFormatVersion: 2010-09-09
Description: This CF template consist of the infrastructure of a 3-tier web application

Resources:
  #making vpc
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      Tags:
        - Key: Name
          Value: my-vpc-01
  
  #creating public subnet
  myPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: myVPC
      CidrBlock: 192.168.0.0/24
      AvailabilityZone: us-east-2a
      Tags:
        - Key: Name
          Value: my-public-subnet-1
  
  #creating private subnet - 1
  myPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 192.168.1.0/24
      AvailabilityZone: us-east-2b
      Tags:
        - Key: Name
          Value: my-private-subnet-1
  
  #creating private subnet - 2
  myPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 192.168.2.0/24
      AvailabilityZone: us-east-2c
      Tags:
        - Key: Name
          Value: my-private-subnet-2
  
  #creating Internet Gateway
  myIG1:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: my-IG-1

  #attaching vpc to igw
  VpcToIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: myIG1
      VpcId: 
        Ref: myVPC
  
  #creating route table for public subnet
  publicSubnetRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: 
        Ref: myVPC
      Tags:
        - Key: Name
          Value: publicSubnetRT
  # Associating the public subnet to the public route table
  publicSubnetRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: publicSubnetRT
      SubnetId:
        Ref: myPublicSubnet1

  #creating route table for private subnet
  privateSubnetRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: 
        Ref: myVPC
      Tags:
        - Key: Name
          Value: privateSubnetRT
  #creating association between private subnets and route tables
  privateSubnetRTAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: privateSubnetRT
      SubnetId:
        Ref: myPrivateSubnet1
  privateSubnetRTAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: privateSubnetRT
      SubnetId:
        Ref: myPrivateSubnet2

  #creating nat gateway with elastic IP
  NATGElasticIP: #creating elastic Ip for Nat Gateway
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NATGateway: #creating Nat Gateway
   Type: AWS::EC2::NatGateway
   Properties:
      AllocationId: !GetAtt NATGElasticIP.AllocationId
      SubnetId: !Ref myPublicSubnet1
      Tags:
      - Key: Name
        Value: myNatGateway-1
  NATGatewayRoute: #Creating the route from private RT to nat gateway
   DependsOn: NATGateway
   Type: AWS::EC2::Route
   Properties:
      RouteTableId: !Ref privateSubnetRT
      DestinationCidrBlock: '0.0.0.0/0'
      NatGatewayId: !Ref NATGateway

    
    
Outputs:
  myVPCId:
    Description: Id of the VPC created
    Value:
      Ref: myVPC
  
  myPublicSubnet1Id:
    Description: Id of the my-public-subnet-1
    Value:
      Ref: myPublicSubnet1
  myPrivateSubnet1Id:
    Description: Id of the my-private-subnet-1
    Value:
      Ref: myPrivateSubnet1
  myPrivateSubnet2Id:
    Description: Id of the my-private-subnet-2
    Value:
      Ref: myPrivateSubnet2

  myIG1Id:
    Description: Id of the Internet Gateway
    Value:
      Ref: myIG1
  




